# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Hayley Anderson
tagline: "Ruby developer based in New York City"
description: "I'm a Ruby developer based in New York City, and this is my attempt at blogging."
url: http://blog.hayleyanderson.us
baseurl: /

author:
  name:           "Hayley Anderson"
  email:          "hayleyanderson@zoho.com"
  url:            http://hayleyanderson.us

paginate:         5

# Custom vars
