# Dependencies
markdown: redcarpet
highlighter: pygments
category_archive:
  slugify: true
gems:
  - jekyll-sitemap

# Permalinks
permalink: /:year/:month/:day/:title/
relative_permalinks: true

# Setup
title: "Hayley Anderson"
description: "I'm a software engineer in New York City, and this is my attempt at blogging."
url: http://blog.hayleyanderson.us

author:
  name:           "Hayley Anderson"
  email:          "hayleyanderson@zoho.com"
  url:            http://blog.hayleyanderson.us
