# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: /:year/:month/:day/:title/
relative_permalinks: true

# Setup
title: Hayley Anderson
tagline: "Software Engineer in NYC"
description: "I'm a software engineer in New York City, and this is my attempt at blogging."
url: http://blog.hayleyanderson.us
baseurl: /

author:
  name:           "Hayley Anderson"
  email:          "hayleyanderson@zoho.com"
  url:            http://hayleyanderson.us

paginate:         3

# Custom vars
