# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Hayley Anderson
tagline: "Learning Ruby and Loving New York"
description: "Hi, I'm a Ruby on Rails student at Metis in New York City. This is my blog about what I'm learning."
url: http://blog.hayleyanderson.us
baseurl: /

author:
  name:           "Hayley Anderson"
  url:            http://hayleyanderson.us

paginate:         5

# Custom vars