# Dependencies
markdown: redcarpet
highlighter: pygments

# Permalinks
permalink: pretty
relative_permalinks: true

# Setup
title: Hayley Anderson
tagline: 'Hayley Anderson'
description: "Hi, I'm a Ruby on Rails student at Metis in New York City. I'm going to be blogging here about what I'm learning."
url: http://blog.hayleyanderson.us
baseurl: /

author:
  name:           'Hayley Anderson'
  url:            http://hayleyanderson.us

paginate:         5

# Custom vars