# Dependencies
markdown: redcarpet
highlighter: pygments
gems:
  - jekyll-archives
  - jekyll-sitemap

# Setup
title: "Hayley Anderson"
description: "I'm a software engineer in New York City, and this is my attempt at blogging."
url: http://blog.hayleyanderson.us

author:
  name:           "Hayley Anderson"
  email:          "hayleyanderson@zoho.com"
  url:            http://blog.hayleyanderson.us

# Permalinks
permalink: /:year/:month/:day/:title/
relative_permalinks: true

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: 'category_archive'
  permalinks:
    category: /:name/
