# Dependencies
plugins: [jekyll-gist, jekyll-paginate, pygments, redcarpet]

# Permalinks
permalink: pretty

# Setup
title: Hayley Anderson
tagline: "Software Engineer in NYC"
description: "I'm a software engineer in New York City, and this is my attempt at blogging."
url: http://blog.hayleyanderson.us
baseurl: /

author:
  name:           "Hayley Anderson"
  email:          "hayleyanderson@zoho.com"
  url:            http://hayleyanderson.us

paginate:         5

# Custom vars
